CREATE TABLE PERSONA (
    ID BIGINT  AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    GENERO VARCHAR(10),
    EDAD INT,
    IDENTIFICACION VARCHAR(20) NOT NULL UNIQUE,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(15)
);

CREATE TABLE CLIENTE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTRASENA VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL
    
);



INSERT INTO PERSONA (NOMBRE, GENERO, EDAD, IDENTIFICACION, DIRECCION, TELEFONO)
VALUES ('Jose Lema', 'Masculino', 30, '3335435', 'Otavalo sn y principal', '098254785');

INSERT INTO PERSONA (NOMBRE, GENERO, EDAD, IDENTIFICACION, DIRECCION, TELEFONO)
VALUES ('Marianela Montalvo', 'Femenino', 30, '56416565', 'Amazonas y NNUU', '097548965');

INSERT INTO PERSONA (NOMBRE, GENERO, EDAD, IDENTIFICACION, DIRECCION, TELEFONO)
VALUES ('Juan Osorio', 'Masculino', 30, '65561566', '13 junio y Equinoccial', '098874587');



INSERT INTO CLIENTE (ID,ESTADO,CONTRASENA)
VALUES (1,'Activo','ABC123');

INSERT INTO CLIENTE (ID,ESTADO,CONTRASENA)
VALUES (2,'Activo','547457');

INSERT INTO CLIENTE (ID,ESTADO,CONTRASENA)
VALUES (3,'Activo','ABCTTH123');








